# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CounterWeight

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Hierarchy(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Hierarchy()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHierarchy(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Hierarchy
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Hierarchy
    def Nodes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FbxLibra.CounterWeight.Node import Node
            obj = Node()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Hierarchy
    def NodesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Hierarchy
    def NodesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def HierarchyStart(builder):
    builder.StartObject(1)

def Start(builder):
    HierarchyStart(builder)

def HierarchyAddNodes(builder, nodes):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(nodes), 0)

def AddNodes(builder, nodes):
    HierarchyAddNodes(builder, nodes)

def HierarchyStartNodesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNodesVector(builder, numElems):
    return HierarchyStartNodesVector(builder, numElems)

def HierarchyEnd(builder):
    return builder.EndObject()

def End(builder):
    return HierarchyEnd(builder)
